from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
from Bio.Seq import Seq
from Bio.Alphabet import IUPAC

fileObj = open("output.fasta", "w")

proteinSeq = \
    'MFADRWLFSTNHKDIGTLYLLFGAWAGVLGTALSLLIRAELGQPGN' \
    'LLGNDHIYNVIVTAHAFVMIFFMVMPIMIGGFGNWLVPLMIGAPDM' \
    'AFPRMNNMSFWLLPPSLLLLLASAMVEAGAGTGWTVYPPLAGNYSH' \
    'PGASVDLTIFSLHLAGVSSILGAINFITTIINMKPPAMTQYQTPLF' \
    'VWSVLITAVLLLLSLPVLAAGITMLLTDRNLNTTFFDPAGGGDPIL' \
    'YQHLFWFFGHPEVYILILPGFGMISHIVTYYSGKKEPFGYMGMVWA' \
    'MMSIGFLGFIVWAHHMFTVGMDVDTRAYFTSATMIIAIPTGVKVFS' \
    'WLATLHGSNMKWSAAVLWALGFIFLFTVGGLTGIVLANSSLDIVLH' \
    'DTYYVVAHFHYVLSMGAVFAIMGGFIHWFPLFSGYTLDQTYAKIHF' \
    'TIMFIGVNLTFFPQHFLGLSGMPRRYSDYPDAYTTWNILSSVGSFI' \
    'SLTAVMLMIFMIWEAFASKRKVLMVEEPSMNLEWLYGCPPPYHTFE' \
    'EPVYMKS'

seqObj = Seq(proteinSeq, IUPAC.protein)
proteinObj = SeqRecord(seqObj, id="TEST")
SeqIO.write([proteinObj, ], fileObj, 'fasta')
fileObj.close()
